### ISSUE TITLE
Opening multitree RaxML bootstrap file results in NAN tree with labels

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki_web#13]
<img width="334" alt="screen shot 2017-12-12 at 11 39 40 am" src="https://user-images.githubusercontent.com/17452755/33896641-53bef06c-df31-11e7-871a-e0f141e7ab9b.png">

**Comment by mooreryan** [comment]
Can you send me the tree file?  You can attach it here if you want.

**Comment by mooreryan** [comment]
Should be fixed now (1aca07e62d4ea66403f40e9721955639e78b085c).
