### ISSUE TITLE
Error in branch width when mapping file has blanks

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki_web#17]
When mapping file column "branch width" has empty cells, iroki does not correctly propagate the branch width only to common branches and nodes. The cells with non-default values are propagated back to the tree root regardless. When default thickness values are inserted, then it behaves normally.

**Comment by mooreryan** [comment]
This should be fixed as of 831654b6113496c2643ae1e895c43de40a99855b.  @seanmcallister Can you double check it?

**Comment by seanmcallister** [comment]
Fixed
