### ISSUE TITLE
Strange behavior with defaults in multiple sessions with and without mapping file options

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki_web#18]
Modifying defaults before loading a mapping file that freezes them leads to new "defaults" based on the prior session. I would suggest a full viewer reset when loading new tree files to avoid this.

**Comment by mooreryan** [comment]
This should be fixed as of 71f86643599898e6803da08a9faa345f9e8afdc1.

Reopen if it is still wonky.
