### ISSUE TITLE
Leaf label and leaf dot size cannot be modified with the slider

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki_web#21]
When importing a mapping file either 1) with no values for leaf_label_size or leaf_dot_size or 2) with those columns removed from the mapping file altogether. The slider is non functional for changing the values. It does still work for inner dot and label sizes.

**Comment by mooreryan** [comment]
@seanmcallister Try this again.  I think the last update should have fixed this.

**Comment by seanmcallister** [comment]
Fixed.
