### ISSUE TITLE
Reset button doesn't reset everything

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki_web#22]
For instance, the tree type is saved from the previous session.

**Comment by seanmcallister** [comment]
And leaf dots...

**Comment by mooreryan** [comment]
This should be fixed (cd1a13f236e9114011b60a2be6ffc6196fbc8033).  @seanmcallister Could you close the issue if it is working for you now?

**Comment by seanmcallister** [comment]
The issue from before was fixed.
