### ISSUE TITLE
Inner node dots should be able to show bootstrap support

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki_web#8]
Many people would use:

solid dot >= 70
solid line, hollow interior >= 50
dotted line >= 40
no dot < 40

**Comment by mooreryan** [comment]
I've got two levels done (solid and hollow interior with solid line) as of 180bd7a1581e340d55723eb8d856538d5ca0f711.  The cutoffs can be set by the user.    I moved the dotted line suggestion into the feature requests section for now.
